matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      encoding: utf-8
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
    sources:
      - "**/*.md"
    default_encoding: utf-8
