matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      encoding: utf-8
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre
    sources:
      - "**/*.md"
    default_encoding: utf-8
